"""
Abstract base classes and value objects for the LLM provider layer.

This module defines the common interface that ALL LLM provider adapters
must implement (ADR-004). No provider-specific SDK imports belong here.

Design goals:
- `LLMProvider` is the only type the rest of the application depends on.
- `LLMResponse` is a value object: immutable, comparable, serializable.
- `ConversationMessage` normalizes the message format across providers
  (Anthropic, Google, and OpenAI all use slightly different schemas).
- Adding a new provider = write a new class that inherits `LLMProvider`.
  Zero changes required anywhere else in the system.
"""

from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import Literal


# ---------------------------------------------------------------------------
# Value objects
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ConversationMessage:
    """
    A single message in a conversation history.

    `role` uses the OpenAI convention ("user" / "assistant") as the canonical
    format. Provider adapters are responsible for mapping to their own schema.

    Attributes:
        role:    "user" for end-customer messages, "assistant" for agent responses.
        content: Plain-text message content.
    """

    role: Literal["user", "assistant"]
    content: str

    def __post_init__(self) -> None:
        if not self.content.strip():
            raise ValueError("ConversationMessage content cannot be empty.")


@dataclass(frozen=True)
class LLMResponse:
    """
    Normalized response from any LLM provider.

    Immutable value object returned by `LLMProvider.generate()`.
    Token counts are used for per-tenant cost tracking (stored in `messages`).

    Attributes:
        content:      Generated text from the model.
        input_tokens: Number of tokens in the input (system + history + user message).
        output_tokens: Number of tokens in the generated response.
        provider:     Provider name ("anthropic" | "google" | "openai").
        model:        Specific model used (e.g. "claude-haiku-4-5").
        cached_tokens: Tokens served from provider cache (Anthropic-specific;
                       0 for other providers). Used to calculate actual cost.
    """

    content: str
    input_tokens: int
    output_tokens: int
    provider: str
    model: str
    cached_tokens: int = field(default=0)

    @property
    def total_tokens(self) -> int:
        """Total tokens consumed in this call."""
        return self.input_tokens + self.output_tokens

    def __str__(self) -> str:
        return (
            f"LLMResponse(provider={self.provider!r}, model={self.model!r}, "
            f"in={self.input_tokens}, out={self.output_tokens}, "
            f"cached={self.cached_tokens})"
        )


# ---------------------------------------------------------------------------
# Abstract provider interface
# ---------------------------------------------------------------------------

class LLMProvider(ABC):
    """
    Abstract base class for all LLM provider adapters.

    Concrete subclasses must implement `generate()` and `stream()`.
    All other application code depends on this interface — never on a
    concrete adapter class. This allows swapping providers without touching
    business logic (ADR-004).

    Provider adapters must:
    1. Map exceptions to `LLMProviderError` subclasses (never leak SDK errors).
    2. Return `LLMResponse` with accurate token counts.
    3. Accept messages in the `ConversationMessage` format and convert internally.
    """

    # Subclasses should override these class-level attributes
    PROVIDER_NAME: str = ""
    DEFAULT_MODEL: str = ""

    @abstractmethod
    async def generate(
        self,
        system_prompt: str,
        messages: list[ConversationMessage],
        *,
        temperature: float = 0.3,
        max_tokens: int = 500,
    ) -> LLMResponse:
        """
        Generate a response from the LLM.

        Args:
            system_prompt: The master system prompt for this tenant's agent.
                           This is the long, static prompt generated by the
                           onboarding engine — eligible for prompt caching.
            messages:      Conversation history in chronological order.
                           The last message is always the user's latest input.
            temperature:   Sampling temperature (0.0 = deterministic, 1.0 = creative).
                           Default 0.3 keeps responses consistent for a business bot.
            max_tokens:    Maximum tokens to generate in the response.

        Returns:
            LLMResponse with content and token counts.

        Raises:
            LLMProviderError: Any provider-level failure (auth, rate limit, timeout).
        """
        ...

    @abstractmethod
    async def stream(
        self,
        system_prompt: str,
        messages: list[ConversationMessage],
        *,
        temperature: float = 0.3,
        max_tokens: int = 500,
    ) -> AsyncIterator[str]:
        """
        Stream the LLM response token by token.

        Yields text chunks as they are generated. Useful for the live
        chat-preview UI in the dashboard (real-time feedback to the business
        owner while they configure the agent).

        Raises:
            LLMProviderError: Any provider-level failure.
        """
        ...

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} provider={self.PROVIDER_NAME!r} model={self.DEFAULT_MODEL!r}>"
